import "@/css/globals.css";
import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import LeaderBoard from "@/components/LeaderBoard";

const inter = Noto_Sans({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <Header />
        <div className="flex flex-wrap-reverse gap-6 grow">
          <div className="md:w-3/4 sm:2/3">{children}</div>
          <aside>
            <LeaderBoard />
          </aside>
        </div>
        <Footer />
      </body>
    </html>
  );
}
