import '@/css/globals.css'
import type { Metadata } from 'next'
import { Noto_Sans } from 'next/font/google'

const inter = Noto_Sans({ subsets: ['latin'], weight:['400', '700'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className='flex flex-wrap-reverse gap-6'>
      <div>{children}</div>
      <aside>aside</aside>
      </div>  
      </body>
    </html>
  )
}
